extends:
  # recommended extensions with prettier: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  # import extension: https://github.com/benmosher/eslint-plugin-import
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./packages/**/tsconfig.json
plugins:
  - "@typescript-eslint"
  - import
rules:
  # import rules
  "import/no-default-export": "error"
  "import/order": ["error", {"newlines-between": "always"}]
  # disabled rules
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/explicit-function-return-type": off
  # other rules
  "@typescript-eslint/unbound-method": ["error", { "ignoreStatic": true }]
