name: all packages
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install packages
      run: yarn install
    - name: Run tests
      run: |
        yarn build
        yarn dlint
        yarn test:all
